name: my-cicd-workflow example
on:
  push:
    branches: [ "main" ]
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Build with Maven
      run: mvn clean install -f MyWebApp/pom.xml
    - name: Upload WAR File
      uses: actions/upload-artifact@v2
      with:
        name: MyWebApp
        path: target/*.war # Change this to match your WAR file path
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v1
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=my-devops-coach
          -Dsonar.projectKey=myWebAppFromCoach
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    - name: slack - GitHub Actions Slack integration
      uses: act10ns/slack@v2.0.0
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#feb-2024-weekend-batch'
      if: always()

